Error
java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:164)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:814)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2088)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1903)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1734)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1680)
	at l.ܿۘ۬.<init>(64G1:34)
	at l.ۨۘ۬.᩶(E4X1:35)
	at l.᩶ܶ᩹.᩶(E166:237)
	at l.᩵ۗ᩹.call(Y14Y:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1100)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:1572)

